# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hkufui' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hkufui
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'hkufuiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hkufui-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hkufui-tvOS

  target 'hkufui-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
